FROM ubuntu:14.04

MAINTAINER "Petr Simecek" lamparna@gmail.com

# devtools external dependencies
RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install -y bowtie && \
    apt-get install -y samtools